import { DEFAULT_TWEAKS } from "./ThemeProvider";

export const SAAS_PRESETS = {
  dashboard: {
    id: "dashboard",
    name: "Ops dashboard",
    tagline: "KPI strip, charts & service health with collapsible nav",
    suggestedTheme: "soft-glass",
    why: "Shows the Dashboard shell collapse control — icon rail for more canvas, outside Taste.",
    path: "/saas/dashboard",
    tweaks: {
      ...DEFAULT_TWEAKS,
      glassBlur: 20,
      glassOpacity: 0.52,
      accentHue: 199,
      hoverLift: 0.25,
      shadowIntensity: 1,
    },
  },
  autumn: {
    id: "autumn",
    name: "Autumn Insight",
    tagline: "Ops analytics with glassy cards & dot-matrix trends",
    suggestedTheme: "soft-glass",
    why: "Soft Glass is the kit core — keep frost chrome, use orange only for the pixel chart.",
    path: "/saas/autumn",
    tweaks: {
      ...DEFAULT_TWEAKS,
      glassBlur: 22,
      glassOpacity: 0.55,
      accentHue: 24,
      ringShine: 0.85,
      ringGlow: 0.5,
      hoverLift: 0.3,
      shadowIntensity: 1,
      motionStrength: 1,
      radiusScale: 1,
      rimStrength: 0.9,
    },
  },
  travel: {
    id: "travel",
    name: "Voyage Travel CRM",
    tagline: "Trips, guests, itineraries & concierge pipeline",
    suggestedTheme: "crystal",
    why: "Crystal keeps travel UI airy — maps, bookings, and guest cards stay light.",
    path: "/saas/travel",
    tweaks: {
      ...DEFAULT_TWEAKS,
      glassBlur: 20,
      glassOpacity: 0.5,
      accentHue: 198,
      ringShine: 0.9,
      hoverLift: 0.3,
      motionStrength: 1,
    },
  },
  finance: {
    id: "finance",
    name: "Ledger Finance",
    tagline: "Cashflow, portfolios, invoices & risk",
    suggestedTheme: "midnight",
    why: "Midnight keeps money UI calm and dense — amber accents for gains without glare.",
    path: "/saas/finance",
    tweaks: {
      ...DEFAULT_TWEAKS,
      glassBlur: 18,
      glassOpacity: 0.62,
      accentHue: 32,
      ringShine: 0.6,
      ringGlow: 0.4,
      hoverLift: 0.2,
      shadowIntensity: 0.9,
      motionStrength: 0.9,
    },
  },
  kanban: {
    id: "kanban",
    name: "Flowboard",
    tagline: "Kanban delivery board with KPI strip",
    suggestedTheme: "aurora",
    why: "Aurora gives board columns color energy while KPIs stay scannable.",
    path: "/saas/kanban",
    tweaks: {
      ...DEFAULT_TWEAKS,
      glassBlur: 22,
      glassOpacity: 0.56,
      accentHue: 280,
      ringShine: 1.05,
      ringGlow: 0.7,
      hoverLift: 0.4,
      motionStrength: 1.15,
      radiusScale: 1.05,
    },
  },
};
