/**
 * Frosted SoftMark lab catalog (explore/icons-frosted only — not a kit export).
 *
 * Lab surface is Bare: shaped / stroke glass marks (Arrow, User, Bell, Chart).
 * Tiled Soft Complex plates stay in frostedIcons.jsx as origin artwork only.
 * Geometry: viewBox 0 0 48 48; default tile 9/9/30/30 rx≈10
 */

export const FROSTED_VERSIONS = ["bare", "tiled"];

export const FROSTED_STANDARDS = {
  viewBox: "0 0 48 48",
  tile: { x: 9, y: 9, w: 30, h: 30, rx: 10 },
  glyphInset: { min: 14, max: 34 },
  strokeWidth: { min: 2.4, max: 3.4 },
  bareGlyphScale: 1,
  layers: ["extrude", "face", "glyph", "specular"],
  checklist: [
    "Lab reviews Bare SoftMark only (shaped / SoftStrokeMark) — not plate-off TileMarks",
    "Origin silhouettes stay intact; do not overlay scaled cores or hard Spec H/V cuts on arrows",
    "Bright core accent on interior detail; theme via currentColor + --soft-cx-*",
    "No raw hex fills — gradients or CSS variables",
    "Safe area ~6–42; name matches silhouette; Close/Check/Plus are stroke weight peers",
    "Do not merge this catalog into main; Phosphor remains the shipped icon set",
  ],
};

export const FROSTED_CATEGORIES = [
  {
    id: "nav",
    label: "Navigation & layout",
    hint: "Shell, sidebar, and page structure",
    icons: [
      "home",
      "dashboard",
      "grid",
      "layout",
      "sidebar",
      "panels",
      "table",
      "list",
      "columns",
      "menu",
    ],
  },
  {
    id: "actions",
    label: "Actions & chrome",
    hint: "Toolbars, forms, and dense controls",
    icons: [
      "search",
      "filter",
      "sort",
      "more",
      "close",
      "check",
      "plus",
      "minus",
      "edit",
      "trash",
      "copy",
      "save",
      "download",
      "upload",
      "refresh",
      "externalLink",
      "arrowLeft",
      "arrowRight",
      "arrowUp",
      "arrowDown",
      "chevronRight",
      "chevronLeft",
    ],
  },
  {
    id: "people",
    label: "People & access",
    hint: "Accounts, teams, and security",
    icons: [
      "user",
      "users",
      "userPlus",
      "lock",
      "unlock",
      "shield",
      "key",
      "eye",
      "eyeOff",
      "login",
      "logout",
    ],
  },
  {
    id: "comms",
    label: "Communication",
    hint: "Inbox, chat, and notifications",
    icons: ["mail", "send", "inbox", "chat", "bell", "phone", "link", "share", "at"],
  },
  {
    id: "data",
    label: "Data & commerce",
    hint: "Analytics, billing, and storefront",
    icons: [
      "chart",
      "trendingUp",
      "trendingDown",
      "pieChart",
      "activity",
      "report",
      "wallet",
      "creditCard",
      "dollar",
      "cart",
      "receipt",
      "package",
    ],
  },
  {
    id: "content",
    label: "Content & places",
    hint: "Files, media, and location",
    icons: [
      "calendar",
      "clock",
      "folder",
      "file",
      "files",
      "image",
      "database",
      "cloud",
      "server",
      "tag",
      "bookmark",
      "star",
      "flag",
      "mapPin",
      "globe",
    ],
  },
  {
    id: "system",
    label: "System & status",
    hint: "Settings, help, and feedback",
    icons: [
      "settings",
      "info",
      "help",
      "alert",
      "warning",
      "ban",
      "sparkles",
      "rocket",
      "zap",
      "layers",
      "code",
      "terminal",
      "support",
      "book",
      "power",
    ],
  },
];

export const FROSTED_ICON_KEYS = FROSTED_CATEGORIES.flatMap((c) => c.icons);

export const FROSTED_LABELS = {
  home: "Home",
  dashboard: "Dashboard",
  grid: "Grid",
  layout: "Layout",
  sidebar: "Sidebar",
  panels: "Panels",
  table: "Table",
  list: "List",
  columns: "Columns",
  menu: "Menu",
  search: "Search",
  filter: "Filter",
  sort: "Sort",
  more: "More",
  close: "Close",
  check: "Check",
  plus: "Plus",
  minus: "Minus",
  edit: "Edit",
  trash: "Trash",
  copy: "Copy",
  save: "Save",
  download: "Download",
  upload: "Upload",
  refresh: "Refresh",
  externalLink: "External",
  arrowLeft: "Arrow left",
  arrowRight: "Arrow right",
  arrowUp: "Arrow up",
  arrowDown: "Arrow down",
  chevronRight: "Chevron right",
  chevronLeft: "Chevron left",
  user: "User",
  users: "Users",
  userPlus: "User plus",
  lock: "Lock",
  unlock: "Unlock",
  shield: "Shield",
  key: "Key",
  eye: "Eye",
  eyeOff: "Eye off",
  login: "Login",
  logout: "Logout",
  mail: "Mail",
  send: "Send",
  inbox: "Inbox",
  chat: "Chat",
  bell: "Bell",
  phone: "Phone",
  link: "Link",
  share: "Share",
  at: "Mention",
  chart: "Chart",
  trendingUp: "Trending up",
  trendingDown: "Trending down",
  pieChart: "Pie chart",
  activity: "Activity",
  report: "Report",
  wallet: "Wallet",
  creditCard: "Card",
  dollar: "Dollar",
  cart: "Cart",
  receipt: "Receipt",
  package: "Package",
  calendar: "Calendar",
  clock: "Clock",
  folder: "Folder",
  file: "File",
  files: "Files",
  image: "Image",
  database: "Database",
  cloud: "Cloud",
  server: "Server",
  tag: "Tag",
  bookmark: "Bookmark",
  star: "Star",
  flag: "Flag",
  mapPin: "Map pin",
  globe: "Globe",
  settings: "Settings",
  info: "Info",
  help: "Help",
  alert: "Alert",
  warning: "Warning",
  ban: "Ban",
  sparkles: "Sparkles",
  rocket: "Rocket",
  zap: "Zap",
  layers: "Layers",
  code: "Code",
  terminal: "Terminal",
  support: "Support",
  book: "Book",
  power: "Power",
};
