/**
 * Soft UI icon languages — hub: all review sets.
 */

export const ICON_STYLE_GROUPS = [
{ id: "line", label: "Line & fill", hint: "UI chrome weights — toolbars, nav, dense controls" },
{ id: "glass", label: "Glass & depth", hint: "Frosted / soft-3D language inspired by your glass icon refs" },
{ id: "chrome", label: "Chrome neon", hint: "Chrome Color Icons — Neon Reflections (kit-friendly SVG reads)" },
{
    id: "glassy-mix",
    label: "Glassy mix",
    hint: "Overlapping translucent gradients that blend where shapes meet",
  },,
];

export const ICON_STYLES = [
  // —— Line & fill ——
{
    id: "soft-stroke",
    group: "line",
    name: "Soft Stroke",
    tagline: "Rounded 1.75 stroke — airy glass chrome",
    fit: "Closest to frosted UI outlines and soft buttons.",
    mode: "stroke",
    strokeWidth: 1.75,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    opacity: 1,
  },
  {
    id: "soft-fill",
    group: "line",
    name: "Soft Fill",
    tagline: "Solid glyphs with gentle mass",
    fit: "Reads clearly in rings, nav rails, and dense toolbars.",
    mode: "fill",
    opacity: 1,
  },
  {
    id: "glass-duotone",
    group: "line",
    name: "Glass Duotone",
    tagline: "Soft fill wash + crisp stroke rim",
    fit: "Matches sheen / glass rings — brand-forward moments.",
    mode: "duotone",
    strokeWidth: 1.55,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    underlay: { opacity: 0.28 },
  },
  {
    id: "clay-bold",
    group: "line",
    name: "Clay Bold",
    tagline: "Chunky 2.35 rounded stroke",
    fit: "Soft / neumorphic weight — friendly SaaS samples.",
    mode: "stroke",
    strokeWidth: 2.35,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    opacity: 1,
  },
  {
    id: "crystal-line",
    group: "line",
    name: "Crystal Line",
    tagline: "Hairline 1.25 geometric stroke",
    fit: "Crystal / dusk themes — precise, quieter chrome.",
    mode: "stroke",
    strokeWidth: 1.25,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    opacity: 0.92,
  },,
  // —— Glass & depth ——
{
    id: "frost-shell",
    group: "glass",
    name: "Frost Shell",
    tagline: "Translucent plate + solid glyph core",
    fit: "Closest 2D read of the frosted calendar / list tiles in your refs.",
    mode: "frost-shell",
    plateRx: 6.5,
    plateOpacityTop: 0.42,
    plateOpacityBottom: 0.12,
    rimOpacity: 0.55,
    glyphOpacity: 0.95,
  },
  {
    id: "iso-glass",
    group: "glass",
    name: "Iso Glass",
    tagline: "Soft isometric tilt + gradient glass body",
    fit: "Echoes the 3⁄4 frosted slabs without leaving SVG/theme tokens.",
    mode: "iso-glass",
    plateRx: 6,
    plateOpacityTop: 0.5,
    plateOpacityBottom: 0.14,
    rimOpacity: 0.65,
    skewX: -8,
    skewY: 4,
    glyphOpacity: 0.98,
  },
  {
    id: "glow-core",
    group: "glass",
    name: "Glow Core",
    tagline: "Luminous accent core in a soft halo",
    fit: "Matches the glowing blue centers / check discs in the refs.",
    mode: "glow-core",
    haloOpacity: 0.22,
    glyphOpacity: 1,
  },
  {
    id: "acrylic-slab",
    group: "glass",
    name: "Acrylic Slab",
    tagline: "Thick rounded tile with inset mark",
    fit: "Card-like glass blocks — great for KPI / empty-state hero marks.",
    mode: "acrylic-slab",
    plateRx: 7,
    plateOpacityTop: 0.55,
    plateOpacityBottom: 0.18,
    rimOpacity: 0.7,
    insetScale: 0.72,
    glyphOpacity: 1,
  },
  {
    id: "prism-soft",
    group: "glass",
    name: "Prism Soft",
    tagline: "Layered refraction + bright rim catch",
    fit: "Multi-layer glass like the chevrons / X marks — still themeable.",
    mode: "prism-soft",
    plateRx: 6.5,
    plateOpacityTop: 0.35,
    plateOpacityBottom: 0.08,
    rimOpacity: 0.75,
    backOffset: 1.4,
    glyphOpacity: 0.9,
  },,
  // —— Chrome neon ——
{
    id: "chrome-neon",
    group: "chrome",
    name: "Chrome Neon",
    tagline: "Liquid metal body + cyan→magenta sheen",
    fit: "Closest SVG read of the polished chrome + neon reflection boards.",
    mode: "chrome-neon",
    glow: 0.55,
  },
  {
    id: "neon-rim",
    group: "chrome",
    name: "Neon Rim",
    tagline: "Cool top / warm bottom rim light",
    fit: "Split lighting like the basketball & rocket — accent + magenta rim.",
    mode: "neon-rim",
    strokeWidth: 2.1,
    glow: 0.45,
  },
  {
    id: "liquid-metal",
    group: "chrome",
    name: "Liquid Metal",
    tagline: "Brushed radial chrome with specular catch",
    fit: "Speech-bubble style radial metal — works on dusk / midnight.",
    mode: "liquid-metal",
    glow: 0.35,
  },
  {
    id: "iridescent",
    group: "chrome",
    name: "Iridescent",
    tagline: "Diagonal neon gradient face",
    fit: "Lightning-bolt energy — accent through pink iridescence.",
    mode: "iridescent",
    glow: 0.5,
  },
  {
    id: "halo-chrome",
    group: "chrome",
    name: "Halo Chrome",
    tagline: "Chrome glyph in a soft neon aura",
    fit: "Hero / empty-state marks — pops on dark themes.",
    mode: "halo-chrome",
    glow: 0.65,
  },,
  // —— Glassy mix ——
{
    id: "triad-mix",
    group: "glassy-mix",
    name: "Triad Mix",
    tagline: "Blue · magenta · amber layers with multiply blend",
    fit: "Closest read of the overlapping bird mark — brand marks & empty states.",
    mode: "glassy-mix",
    layers: [
      { dx: -2.2, dy: 0.4, stops: ["#1d4ed8", "#38bdf8"], opacity: 0.82 },
      { dx: 0.2, dy: -0.2, stops: ["#db2777", "#f472b6"], opacity: 0.78 },
      { dx: 2.4, dy: 0.6, stops: ["#f59e0b", "#fb923c"], opacity: 0.8 },
    ],
  },
  {
    id: "aurora-mix",
    group: "glassy-mix",
    name: "Aurora Mix",
    tagline: "Cyan · violet · rose drift",
    fit: "Softer glass wash — marketing moments and hero chips.",
    mode: "glassy-mix",
    layers: [
      { dx: -1.8, dy: -0.6, stops: ["#0891b2", "#67e8f9"], opacity: 0.75 },
      { dx: 0.4, dy: 0.8, stops: ["#7c3aed", "#c4b5fd"], opacity: 0.72 },
      { dx: 2.0, dy: -0.4, stops: ["#e11d48", "#fb7185"], opacity: 0.7 },
    ],
  },
  {
    id: "duo-mix",
    group: "glassy-mix",
    name: "Duo Mix",
    tagline: "Accent + warm glass double",
    fit: "Taste accent still leads — denser chrome without losing the mix.",
    mode: "glassy-mix",
    layers: [
      { dx: -1.6, dy: 0.2, stops: ["currentColor", "#67e8f9"], opacity: 0.85 },
      { dx: 1.8, dy: 0.4, stops: ["#f472b6", "#fb923c"], opacity: 0.72 },
    ],
  },
  {
    id: "shard-mix",
    group: "glassy-mix",
    name: "Shard Mix",
    tagline: "Wider offsets — sharper glass facets",
    fit: "More separation between layers — reads as cut acrylic.",
    mode: "glassy-mix",
    layers: [
      { dx: -3.0, dy: 0.8, stops: ["#2563eb", "#22d3ee"], opacity: 0.8 },
      { dx: 0, dy: -1.0, stops: ["#c026d3", "#f472b6"], opacity: 0.76 },
      { dx: 3.0, dy: 1.0, stops: ["#ea580c", "#fbbf24"], opacity: 0.78 },
    ],
  },
  {
    id: "bloom-mix",
    group: "glassy-mix",
    name: "Bloom Mix",
    tagline: "Tight stack — deep multiply core",
    fit: "Heavy overlap for a dark glassy core like the bird’s center.",
    mode: "glassy-mix",
    layers: [
      { dx: -1.0, dy: 0.2, stops: ["#1e40af", "#38bdf8"], opacity: 0.88 },
      { dx: 0.4, dy: 0, stops: ["#be185d", "#f9a8d4"], opacity: 0.84 },
      { dx: 1.2, dy: 0.4, stops: ["#c2410c", "#fcd34d"], opacity: 0.82 },
    ],
  },,
];

export function getIconStyle(id) {
  return ICON_STYLES.find((s) => s.id === id) || ICON_STYLES[0];
}

export function stylesInGroup(groupId) {
  return ICON_STYLES.filter((s) => s.group === groupId);
}
