/**
 * Soft UI Kit — component registry (shadcn-style catalog).
 * Used by Components page for search, filters, and docs anchors.
 */

export const COMPONENT_CATEGORIES = [
  { id: "all", label: "All" },
  { id: "layout", label: "Layout" },
  { id: "forms", label: "Forms" },
  { id: "data", label: "Data display" },
  { id: "feedback", label: "Feedback" },
  { id: "overlay", label: "Overlay" },
  { id: "navigation", label: "Navigation" },
  { id: "charts", label: "Charts" },
  { id: "effects", label: "Effects" },
];

export const COMPONENT_REGISTRY = [
  {
    id: "button",
    name: "Button",
    category: "forms",
    description: "Primary actions with outline, soft, ghost, link, and danger variants.",
    tags: ["cta", "action"],
    variants: ["primary", "secondary", "outline", "soft", "ghost", "link", "danger"],
    sizes: ["sm", "md", "lg"],
    animated: true,
  },
  {
    id: "icon-button",
    name: "Icon Button",
    category: "forms",
    description: "Compact icon-only control for toolbars.",
    tags: ["toolbar"],
    variants: ["ghost", "glass"],
    animated: true,
  },
  {
    id: "input",
    name: "Input",
    category: "forms",
    description: "Text field with label, hint, and error states.",
    tags: ["form", "text"],
    animated: false,
  },
  {
    id: "form-field",
    name: "Form Field",
    category: "forms",
    description: "Composable label + control + hint/error wrapper.",
    tags: ["form", "compose"],
    animated: false,
  },
  {
    id: "input-group",
    name: "Input Group",
    category: "forms",
    description: "Prefixed/suffixed inputs for currency, domains, search.",
    tags: ["form", "crm"],
    animated: false,
  },
  {
    id: "password-input",
    name: "Password Input",
    category: "forms",
    description: "Password field with show/hide toggle.",
    tags: ["form", "auth"],
    animated: true,
  },
  {
    id: "textarea",
    name: "Textarea",
    category: "forms",
    description: "Multi-line text entry.",
    tags: ["form"],
    animated: false,
  },
  {
    id: "select",
    name: "Select",
    category: "forms",
    description: "Native select styled to the glass system.",
    tags: ["form"],
    animated: false,
  },
  {
    id: "checkbox",
    name: "Checkbox",
    category: "forms",
    description: "Boolean selection with soft inset track.",
    tags: ["form"],
    animated: true,
  },
  {
    id: "radio",
    name: "Radio",
    category: "forms",
    description: "Single choice within a group.",
    tags: ["form"],
    animated: true,
  },
  {
    id: "switch",
    name: "Switch",
    category: "forms",
    description: "Animated on/off control.",
    tags: ["form", "toggle"],
    animated: true,
  },
  {
    id: "slider",
    name: "Slider",
    category: "forms",
    description: "Range input with neumorphic thumb.",
    tags: ["form", "range"],
    animated: true,
  },
  {
    id: "toggle",
    name: "Toggle",
    category: "forms",
    description: "Pressed-state toggle button.",
    tags: ["form"],
    animated: true,
  },
  {
    id: "toggle-group",
    name: "Toggle Group",
    category: "forms",
    description: "Segmented control for exclusive options.",
    tags: ["form", "filter"],
    animated: true,
  },
  {
    id: "combobox",
    name: "Combobox",
    category: "forms",
    description: "Searchable select with filtered options.",
    tags: ["form", "search"],
    animated: true,
  },
  {
    id: "otp",
    name: "OTP Input",
    category: "forms",
    description: "One-time passcode digit cells.",
    tags: ["auth"],
    animated: false,
  },
  {
    id: "date-field",
    name: "Date Field",
    category: "forms",
    description: "Native date input in glass field chrome.",
    tags: ["form", "date"],
    animated: false,
  },
  {
    id: "calendar",
    name: "Calendar",
    category: "forms",
    description: "Month grid date picker.",
    tags: ["date"],
    animated: true,
  },
  {
    id: "label",
    name: "Label",
    category: "forms",
    description: "Accessible field label.",
    tags: ["form", "a11y"],
    animated: false,
  },
  {
    id: "card",
    name: "Card",
    category: "layout",
    description: "Glass, flat, and soft surface containers.",
    tags: ["surface"],
    variants: ["glass", "flat", "soft"],
    animated: true,
  },
  {
    id: "dashboard-shell",
    name: "Dashboard shell",
    category: "layout",
    description: "App dashboard layout with collapsible sidebar (icon rail).",
    tags: ["layout", "dashboard", "sidebar", "collapse"],
    animated: true,
  },
  {
    id: "separator",
    name: "Separator",
    category: "layout",
    description: "Visual divider with optional label.",
    tags: ["layout"],
    animated: false,
  },
  {
    id: "scroll-area",
    name: "Scroll Area",
    category: "layout",
    description: "Contained scroll region.",
    tags: ["layout"],
    animated: false,
  },
  {
    id: "aspect-ratio",
    name: "Aspect Ratio",
    category: "layout",
    description: "Ratio-locked media frame.",
    tags: ["layout", "media"],
    animated: false,
  },
  {
    id: "resizable",
    name: "Resizable",
    category: "layout",
    description: "Split panes with draggable handle.",
    tags: ["layout", "dashboard"],
    animated: true,
  },
  {
    id: "collapsible",
    name: "Collapsible",
    category: "layout",
    description: "Expand/collapse content block.",
    tags: ["layout"],
    animated: true,
  },
  {
    id: "accordion",
    name: "Accordion",
    category: "layout",
    description: "Stacked disclosure sections.",
    tags: ["layout", "faq"],
    animated: true,
  },
  {
    id: "skeleton",
    name: "Skeleton",
    category: "feedback",
    description: "Loading placeholder shimmer.",
    tags: ["loading"],
    animated: true,
  },
  {
    id: "badge",
    name: "Badge",
    category: "data",
    description: "Status chips and counts.",
    tags: ["status"],
    variants: ["neutral", "accent", "success", "warning", "danger"],
    animated: true,
  },
  {
    id: "avatar",
    name: "Avatar",
    category: "data",
    description: "User initials or image.",
    tags: ["user"],
    sizes: ["sm", "md", "lg"],
    animated: false,
  },
  {
    id: "table",
    name: "Table",
    category: "data",
    description: "Basic data table.",
    tags: ["crm", "dashboard"],
    animated: true,
  },
  {
    id: "data-table",
    name: "Data Table",
    category: "data",
    description: "Sortable table with selection for CRM/dashboard grids.",
    tags: ["crm", "sort", "select"],
    animated: true,
  },
  {
    id: "progress",
    name: "Progress",
    category: "feedback",
    description: "Linear progress indicator.",
    tags: ["status"],
    animated: true,
  },
  {
    id: "alert",
    name: "Alert",
    category: "feedback",
    description: "Inline status banners.",
    tags: ["status"],
    variants: ["info", "success", "warning", "danger"],
    animated: false,
  },
  {
    id: "toast",
    name: "Toast",
    category: "feedback",
    description: "Transient notifications (stack supported).",
    tags: ["notify"],
    animated: true,
  },
  {
    id: "empty-state",
    name: "Empty State",
    category: "feedback",
    description: "Zero-data placeholder with CTA.",
    tags: ["empty"],
    animated: false,
  },
  {
    id: "dialog",
    name: "Dialog",
    category: "overlay",
    description: "Modal dialog with description and footer actions.",
    tags: ["modal"],
    animated: true,
  },
  {
    id: "alert-dialog",
    name: "Alert Dialog",
    category: "overlay",
    description: "Confirm/destructive modal pattern.",
    tags: ["modal", "confirm"],
    animated: true,
  },
  {
    id: "sheet",
    name: "Sheet",
    category: "overlay",
    description: "Side drawer panel.",
    tags: ["drawer"],
    animated: true,
  },
  {
    id: "dropdown",
    name: "Dropdown Menu",
    category: "overlay",
    description: "Action menu anchored to a trigger.",
    tags: ["menu"],
    animated: true,
  },
  {
    id: "popover",
    name: "Popover",
    category: "overlay",
    description: "Lightweight floating content.",
    tags: ["overlay"],
    animated: true,
  },
  {
    id: "tooltip",
    name: "Tooltip",
    category: "overlay",
    description: "Hover hint bubble.",
    tags: ["hint"],
    animated: true,
  },
  {
    id: "hover-card",
    name: "Hover Card",
    category: "overlay",
    description: "Rich preview on hover.",
    tags: ["preview"],
    animated: true,
  },
  {
    id: "context-menu",
    name: "Context Menu",
    category: "overlay",
    description: "Right-click actions for tables and boards.",
    tags: ["menu", "crm"],
    animated: true,
  },
  {
    id: "command",
    name: "Command",
    category: "navigation",
    description: "Command palette / quick jump.",
    tags: ["search", "keyboard"],
    animated: true,
  },
  {
    id: "tabs",
    name: "Tabs",
    category: "navigation",
    description: "Section switcher.",
    tags: ["nav"],
    animated: true,
  },
  {
    id: "breadcrumb",
    name: "Breadcrumb",
    category: "navigation",
    description: "Hierarchy path.",
    tags: ["nav"],
    animated: false,
  },
  {
    id: "pagination",
    name: "Pagination",
    category: "navigation",
    description: "Page controls for tables.",
    tags: ["nav", "table"],
    animated: true,
  },
  {
    id: "menubar",
    name: "Menubar",
    category: "navigation",
    description: "Horizontal app menu.",
    tags: ["nav", "desktop"],
    animated: true,
  },
  {
    id: "kbd",
    name: "Kbd",
    category: "navigation",
    description: "Keyboard shortcut chip.",
    tags: ["docs"],
    animated: false,
  },
  {
    id: "carousel",
    name: "Carousel",
    category: "data",
    description: "Slide carousel for marketing and galleries.",
    tags: ["media"],
    animated: true,
  },
  {
    id: "bar-chart",
    name: "Bar Chart",
    category: "charts",
    description: "Interactive bars with hover tooltips.",
    tags: ["analytics"],
    animated: true,
  },
  {
    id: "line-chart",
    name: "Line / Area Chart",
    category: "charts",
    description: "SVG line with optional area fill and draw animation.",
    tags: ["analytics"],
    animated: true,
  },
  {
    id: "donut-chart",
    name: "Donut Chart",
    category: "charts",
    description: "Segmented donut with legend hover.",
    tags: ["analytics"],
    animated: true,
  },
  {
    id: "sparkline",
    name: "Sparkline",
    category: "charts",
    description: "Inline trend glyph for KPI cards.",
    tags: ["kpi"],
    animated: true,
  },
  {
    id: "dot-matrix",
    name: "Dot Matrix Chart",
    category: "charts",
    description: "Autumn-style square pixel columns with glass tooltip.",
    tags: ["analytics", "ops"],
    animated: true,
  },
  {
    id: "segmented-bar",
    name: "Segmented Bar",
    category: "charts",
    description: "Multi-segment horizontal breakdown.",
    tags: ["analytics"],
    animated: true,
  },
  {
    id: "timeline-bar",
    name: "Timeline Bar",
    category: "charts",
    description: "Health / milestone timeline with striped tail.",
    tags: ["ops"],
    animated: true,
  },
  {
    id: "heatmap",
    name: "Heatmap",
    category: "charts",
    description: "Intensity grid for activity and ops.",
    tags: ["analytics"],
    animated: true,
  },
  {
    id: "radial-progress",
    name: "Radial Progress",
    category: "charts",
    description: "Circular KPI progress ring.",
    tags: ["kpi"],
    animated: true,
  },
  {
    id: "radial-bars",
    name: "Radial Bars",
    category: "charts",
    description: "Multi-ring activity metrics.",
    tags: ["kpi"],
    animated: true,
  },
  {
    id: "radar-chart",
    name: "Radar Chart",
    category: "charts",
    description: "Spider chart for multi-axis scores.",
    tags: ["analytics"],
    animated: true,
  },
  {
    id: "funnel-chart",
    name: "Funnel Chart",
    category: "charts",
    description: "Conversion stage funnel.",
    tags: ["analytics"],
    animated: true,
  },
  {
    id: "scatter-chart",
    name: "Scatter Chart",
    category: "charts",
    description: "Point cloud for correlation views.",
    tags: ["analytics"],
    animated: true,
  },
  {
    id: "glass-ring",
    name: "Glass Ring",
    category: "effects",
    description: "Shiny glass icon badge with tweakable shine/glow.",
    tags: ["brand", "taste"],
    animated: true,
  },
  {
    id: "border-beam",
    name: "Border Beam",
    category: "effects",
    description: "Animated traveling / pulse border glow (border-beam).",
    tags: ["motion", "npm"],
    animated: true,
  },
  {
    id: "metal-fx",
    name: "Metal FX",
    category: "effects",
    description: "WebGL liquid-metal ring for buttons (metal-fx).",
    tags: ["motion", "npm"],
    animated: true,
  },
];

export function searchComponents(query, category = "all") {
  const q = query.trim().toLowerCase();
  return COMPONENT_REGISTRY.filter((item) => {
    const catOk = category === "all" || item.category === category;
    if (!catOk) return false;
    if (!q) return true;
    const hay = [item.name, item.description, item.id, ...(item.tags || [])]
      .join(" ")
      .toLowerCase();
    return hay.includes(q);
  });
}
