/**
 * Soft UI Kit — UI Kit catalog registry.
 * Charts live on /charts · Effects live on /effects.
 */

export const COMPONENT_CATEGORIES = [
  { id: "all", label: "All" },
  { id: "layout", label: "Layout" },
  { id: "forms", label: "Forms" },
  { id: "data", label: "Data display" },
  { id: "feedback", label: "Feedback" },
  { id: "overlay", label: "Overlay" },
  { id: "navigation", label: "Navigation" },
];

export const COMPONENT_REGISTRY = [
  {
    id: "button",
    name: "Button",
    category: "forms",
    span: "wide",
    description: "Primary actions with outline, soft, ghost, link, and danger variants.",
    tags: ["cta", "action"],
    variants: ["primary", "secondary", "outline", "soft", "ghost", "link", "danger"],
    sizes: ["sm", "md", "lg"],
    animated: true,
  },
  {
    id: "icon-button",
    name: "Icon Button",
    category: "forms",
    span: "wide",
    description: "Compact icon-only control for toolbars.",
    tags: ["toolbar"],
    variants: ["ghost", "glass", "outline"],
    animated: true,
  },
  {
    id: "input",
    name: "Input",
    category: "forms",
    description: "Text field with label, hint, and error states.",
    tags: ["form", "text"],
    animated: false,
  },
  {
    id: "form-field",
    name: "Form Field",
    category: "forms",
    description: "Composable label + control + hint/error wrapper.",
    tags: ["form", "compose", "label"],
    animated: false,
  },
  {
    id: "input-group",
    name: "Input Group",
    category: "forms",
    description: "Prefixed/suffixed inputs for currency, domains, search.",
    tags: ["form", "crm"],
    animated: false,
  },
  {
    id: "password-input",
    name: "Password Input",
    category: "forms",
    description: "Password field with show/hide toggle.",
    tags: ["form", "auth"],
    animated: true,
  },
  {
    id: "textarea",
    name: "Textarea",
    category: "forms",
    description: "Multi-line text entry.",
    tags: ["form"],
    animated: false,
  },
  {
    id: "select",
    name: "Select",
    category: "forms",
    description: "Native select styled to the glass system.",
    tags: ["form"],
    animated: false,
  },
  {
    id: "checkbox",
    name: "Checkbox",
    category: "forms",
    description: "Boolean selection with soft inset track.",
    tags: ["form"],
    animated: true,
  },
  {
    id: "radio",
    name: "Radio",
    category: "forms",
    description: "Single choice within a group.",
    tags: ["form"],
    animated: true,
  },
  {
    id: "switch",
    name: "Switch",
    category: "forms",
    description: "Animated on/off control for settings and forms.",
    tags: ["form", "toggle"],
    animated: true,
  },
  {
    id: "slider",
    name: "Slider",
    category: "forms",
    description: "Range input with neumorphic thumb.",
    tags: ["form", "range"],
    animated: true,
  },
  {
    id: "toggle-group",
    name: "Toggle Group",
    category: "forms",
    description: "Segmented control for exclusive options.",
    tags: ["form", "filter"],
    animated: true,
  },
  {
    id: "combobox",
    name: "Combobox",
    category: "forms",
    description: "Searchable select with filtered options.",
    tags: ["form", "search"],
    animated: true,
  },
  {
    id: "otp",
    name: "OTP Input",
    category: "forms",
    description: "One-time passcode digit cells.",
    tags: ["auth"],
    animated: false,
  },
  {
    id: "date-field",
    name: "Date Field",
    category: "forms",
    description: "Native date input in glass field chrome.",
    tags: ["form", "date"],
    animated: false,
  },
  {
    id: "calendar",
    name: "Calendar",
    category: "forms",
    span: "wide",
    description: "Month grid date picker.",
    tags: ["date"],
    animated: true,
  },
  {
    id: "card",
    name: "Card",
    category: "layout",
    span: "wide",
    description: "Glass, flat, soft, and outline surface containers.",
    tags: ["surface"],
    variants: ["glass", "flat", "soft", "outline"],
    animated: true,
  },
  {
    id: "separator",
    name: "Separator",
    category: "layout",
    description: "Visual divider with optional label.",
    tags: ["layout"],
    animated: false,
  },
  {
    id: "scroll-area",
    name: "Scroll Area",
    category: "layout",
    span: "wide",
    description: "Contained scroll region.",
    tags: ["layout"],
    animated: false,
  },
  {
    id: "aspect-ratio",
    name: "Aspect Ratio",
    category: "layout",
    description: "Ratio-locked media frame.",
    tags: ["layout", "media"],
    animated: false,
  },
  {
    id: "resizable",
    name: "Resizable",
    category: "layout",
    span: "wide",
    description: "Split panes with draggable handle.",
    tags: ["layout", "dashboard"],
    animated: true,
  },
  {
    id: "accordion",
    name: "Accordion",
    category: "layout",
    span: "wide",
    description: "Stacked disclosure sections (covers single collapsible too).",
    tags: ["layout", "faq", "collapsible"],
    animated: true,
  },
  {
    id: "skeleton",
    name: "Skeleton",
    category: "feedback",
    description: "Loading placeholder shimmer.",
    tags: ["loading"],
    animated: true,
  },
  {
    id: "badge",
    name: "Badge",
    category: "data",
    description: "Status chips and counts.",
    tags: ["status"],
    variants: ["neutral", "accent", "success", "warning", "danger"],
    animated: true,
  },
  {
    id: "avatar",
    name: "Avatar",
    category: "data",
    description: "User initials or image.",
    tags: ["user"],
    sizes: ["sm", "md", "lg"],
    animated: false,
  },
  {
    id: "data-table",
    name: "Data Table",
    category: "data",
    span: "full",
    description: "Sortable table with selection for CRM/dashboard grids.",
    tags: ["crm", "sort", "select", "table"],
    animated: true,
  },
  {
    id: "progress",
    name: "Progress",
    category: "feedback",
    description: "Linear progress indicator.",
    tags: ["status"],
    animated: true,
  },
  {
    id: "alert",
    name: "Alert",
    category: "feedback",
    span: "wide",
    description: "Inline status banners.",
    tags: ["status"],
    variants: ["info", "success", "warning", "danger"],
    animated: false,
  },
  {
    id: "toast",
    name: "Toast",
    category: "feedback",
    description: "Transient notifications (stack supported).",
    tags: ["notify"],
    animated: true,
  },
  {
    id: "empty-state",
    name: "Empty State",
    category: "feedback",
    span: "wide",
    description: "Zero-data placeholder with CTA.",
    tags: ["empty"],
    animated: false,
  },
  {
    id: "dialog",
    name: "Dialog",
    category: "overlay",
    span: "wide",
    description: "Modal dialog — includes confirm / destructive patterns.",
    tags: ["modal", "confirm", "alert"],
    animated: true,
  },
  {
    id: "sheet",
    name: "Sheet",
    category: "overlay",
    span: "wide",
    description: "Side drawer panel.",
    tags: ["drawer"],
    animated: true,
  },
  {
    id: "dropdown",
    name: "Dropdown Menu",
    category: "overlay",
    description: "Action menu — also covers right-click / context patterns.",
    tags: ["menu", "context"],
    animated: true,
  },
  {
    id: "popover",
    name: "Popover",
    category: "overlay",
    description: "Lightweight floating content (click or hover rich previews).",
    tags: ["overlay", "hover"],
    animated: true,
  },
  {
    id: "tooltip",
    name: "Tooltip",
    category: "overlay",
    description: "Hover hint bubble.",
    tags: ["hint"],
    animated: true,
  },
  {
    id: "command",
    name: "Command",
    category: "navigation",
    span: "wide",
    description: "Command palette / quick jump.",
    tags: ["search", "keyboard"],
    animated: true,
  },
  {
    id: "tabs",
    name: "Tabs",
    category: "navigation",
    span: "wide",
    description: "Section switcher.",
    tags: ["nav"],
    animated: true,
  },
  {
    id: "breadcrumb",
    name: "Breadcrumb",
    category: "navigation",
    description: "Hierarchy path.",
    tags: ["nav"],
    animated: false,
  },
  {
    id: "pagination",
    name: "Pagination",
    category: "navigation",
    description: "Page controls for tables.",
    tags: ["nav", "table"],
    animated: true,
  },
  {
    id: "menubar",
    name: "Menubar",
    category: "navigation",
    span: "wide",
    description: "Horizontal app menu.",
    tags: ["nav", "desktop"],
    animated: true,
  },
  {
    id: "kbd",
    name: "Kbd",
    category: "navigation",
    description: "Keyboard shortcut chip.",
    tags: ["docs"],
    animated: false,
  },
  {
    id: "carousel",
    name: "Carousel",
    category: "data",
    span: "wide",
    description: "Slide carousel for marketing and galleries.",
    tags: ["media"],
    animated: true,
  },
];

export function searchComponents(query, category = "all") {
  const q = query.trim().toLowerCase();
  return COMPONENT_REGISTRY.filter((item) => {
    const catOk = category === "all" || item.category === category;
    if (!catOk) return false;
    if (!q) return true;
    const hay = [item.name, item.description, item.id, ...(item.tags || [])]
      .join(" ")
      .toLowerCase();
    return hay.includes(q);
  });
}
